#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2019 Logan Gunthorpe
# Copyright (C) 2019 Eideticom Communications Inc.

. tests/nvme/rc

DESCRIPTION="run data verification fio job on an NVMeOF passthru controller"
TIMED=1

requires() {
	_have_program nvme &&
	_have_modules nvme-loop nvmet &&
	_have_configfs &&
	_have_kernel_option NVME_TARGET_PASSTHRU &&
	_have_fio
}

test_device() {
	local subsys="blktests-subsystem-1"
	local ctrldev
	local nsdev
	local port

	echo "Running ${TEST_NAME}"

	_setup_nvmet
	port=$(_nvmet_passthru_target_setup "$subsys")
	nsdev=$(_nvmet_passthru_target_connect "$subsys")

	_run_fio_verify_io --size=950m --filename="${nsdev}"

	_nvmet_passthru_target_disconnect "$subsys"
	_nvmet_passthru_target_cleanup "$port" "$subsys"

	echo "Test complete"
}
